# Generated by Django 6.0.2 on 2026-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no site')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LeadConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.PositiveIntegerField()),
                ('motivo', models.TextField(verbose_name='Motivo da Procura')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAdvogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('oab', models.CharField(help_text='Ex: OAB/SP 123.456', max_length=20)),
                ('foto', models.ImageField(upload_to='advogados/')),
                ('biografia_curta', models.TextField(help_text='Aparece no topo (Hero)')),
                ('biografia_completa', models.TextField(help_text="Aparece na seção 'Sobre'")),
                ('anos_experiencia', models.PositiveIntegerField(default=0)),
                ('casos_concluidos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
